[project]
name = "image-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "huggingface-hub>=0.36.0",
    "paddleocr>=3.3.2",
    "paddlepaddle>=3.2.2",
    "transformers>=4.57.3",
]
